services:
  - type: web
    name: orcax-survey-3060
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: YOUR_MONGODB_URI
